language: rust
rust:
  - stable
os:
  - linux
  - osx
  - windows
cache: cargo

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == stable && "$TRAVIS_OS_NAME" == linux ]]; then
    cargo install cargo-tarpaulin -f
  fi

script:
  - cargo build --verbose
  - cargo test --verbose

after_success: |
  # only run code coverage report for linux system.
  if [[ "$TRAVIS_RUST_VERSION" == stable && "$TRAVIS_OS_NAME" == linux ]]; then
    # the following two lines create and upload a report for codecov.io
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
