language: rust
rust:
  - stable
script:
  - cargo build --verbose
  - cargo test --verbose
os:
  - linux
  - osx
  - windows
cache: cargo

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin -f
    # the following two lines create and upload a report for codecov.io
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
