language: rust
rust:
  - stable
script:
  - cargo build --verbose
  - cargo test --verbose
os:
  - linux
  - osx
  - windows
cache: cargo

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" = stable ]]; then
    bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
    # Calculate test coverage
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
