[package]
name = "hors"
version = "0.6.2"
authors = ["WindSoilder <WindSoilder@outlook.com>"]
edition = "2018"
license = "GPL-3.0"
description = "instant coding answers via the command line(just like howdoi)"
repository = "https://github.com/WindSoilder/hors"
documentation = "https://github.com/WindSoilder/hors/blob/master/README.md"
readme = "./README.md"
keywords = ["http", "client", "cli-tools"]
categories = ["command-line-utilities"]

[dependencies]
clap = "2.33.0"
syntect = "4.1.0"
reqwest = { version="0.10.4", features=["json", "socks", "cookies"] }
tokio = { version = "0.2", features = ["full"] }
select = "0.4.3"
rand = "0.7.3"
log = "0.4.8"
serde = { version = "1.0.106", features = ["derive"] }
bincode = "1.2.1"
dirs = "2.0.2"
url = "2.1.1"

[dev-dependencies]
env_logger = "0.7"
