[package]
name = "hors"
version = "0.3.3"
authors = ["WindSoilder <WindSoilder@outlook.com>"]
edition = "2018"
license = "GPL-3.0"
description = "instant coding answers via the command line(just like howdoi)"
repository = "https://github.com/WindSoilder/hors"
documentation = "https://github.com/WindSoilder/hors/blob/master/README.md"
readme = "./README.md"
keywords = ["http", "client", "cli-tools"]

[dependencies]
clap = "2.33.0"
syntect = "3.2.0"
reqwest = "0.9.16"
select = "0.4.2"
rand = "0.6.5"
log = "0.4.6"
serde = { version = "1.0.91", features = ["derive"] }
bincode = "1.1.4"
dirs = "1.0.5"

[dev-dependencies]
env_logger = "0.6"
